// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCategoryInput struct {
	Name        string `json:"Name"`
	Description string `json:"Description"`
	ImageSrc    string `json:"ImageSrc"`
}

type CreateProductProperty struct {
	Name     string `json:"Name"`
	Code     string `json:"Code"`
	Required bool   `json:"Required"`
}
