// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCategoryInput struct {
	Name        string `json:"Name"`
	Description string `json:"Description"`
	ImageSrc    string `json:"ImageSrc"`
}

type CreateProductInput struct {
	Name        string  `json:"Name"`
	Description string  `json:"Description"`
	ImageSrc    string  `json:"ImageSrc"`
	Price       float64 `json:"Price"`
	CategoryID  *uint   `json:"CategoryID"`
}
